/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BottomNavBar: typeof import('./src/components/BottomNavBar.vue')['default']
    CodeEdit: typeof import('./src/components/CodeEdit.vue')['default']
    DiscoverSkeletonLoader: typeof import('./src/components/DiscoverSkeletonLoader.vue')['default']
    HomeSkeletonLoader: typeof import('./src/components/HomeSkeletonLoader.vue')['default']
    RepoCard: typeof import('./src/components/RepoCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./src/components/SideBar.vue')['default']
    SkeletonLoader: typeof import('./src/components/SkeletonLoader.vue')['default']
    TopNavBar: typeof import('./src/components/TopNavBar.vue')['default']
  }
}
